### ISSUE TITLE
"Not well-formed" error

### ISSUE THREAD

**Issue by jmwoloso** [Juniper/jxmlease#12]
Hello,

When I attempt to parse a WSDL file, I get traceback below, however, running the file through an XML Validator (http://www.w3schools.com/xml/xml_validator.asp) says there are no errors with the structure/content.

Here is the traceback:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/jwolosonovich/.virtualenvs/ztrip_fare_estimator/lib/python3.4/site-packages/jxmlease/xmlparser.py", line 326, in parse
    return Parser(**kwargs)(xml_input)
  File "/home/jwolosonovich/.virtualenvs/ztrip_fare_estimator/lib/python3.4/site-packages/jxmlease/xmlparser.py", line 303, in __call__
    self._parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
```

The beginning of the file looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
```

**Comment by stacywsmith** [comment]
@jmwoloso How are you calling the parser?

You need to either provide a string containing the XML:
```
user@h0$ cat string_example.py 
#/usr/bin/env python
import jxmlease

xml = """<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
</wsdl:definitions>
"""

parser = jxmlease.Parser()
result = parser(xml)
print(result.emit_xml())

user@h0$ python string_example.py 
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:definitions>
```

or a file-like object:
```
user@h0$ cat wsdl.xml 
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
</wsdl:definitions>

user@h0$ cat file_example.py 
#/usr/bin/env python
import jxmlease

f = open('wsdl.xml','r')
parser = jxmlease.Parser()
result = parser(f)
f.close()
print(result.emit_xml())

user@h0$ python file_example.py 
<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://schemas.mtdata.com.au/dispatch/2.20.0/booking" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"></wsdl:definitions>
```

If you try to pass a filename as the input to the parser, you'll get the error you reported:
```
user@h0$ cat broken_example.py 
#/usr/bin/env python
import jxmlease

parser = jxmlease.Parser()
result = parser('wsdl.xml')
print(result.emit_xml())

user@h0$ python broken_example.py 
Traceback (most recent call last):
  File "broken_example.py", line 5, in <module>
    result = parser('wsdl.xml')
  File "/Library/Python/2.7/site-packages/jxmlease/xmlparser.py", line 303, in __call__
    self._parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
```

**Comment by jmwoloso** [comment]
@stacywsmith Ok, that makes sense. Thanks for your help. I was passing the file name directly. I'll open and read it in as a string and try it that way.
